CREATE TABLE EMPLOYEE_MASTER
  (
     ID INTEGER NOT NULL,
     FIRST_NAME VARCHAR(100) NOT NULL,
     LAST_NAME VARCHAR(100) NOT NULL,
     DATE_OF_BIRTH DATE,
     TARGET INTEGER,
	 ROLE_ID INTEGER,
     PRIMARY KEY (ID),
     CONSTRAINT EMPLOYEE_MASTER_ROLE_ID_FKEY FOREIGN KEY (ROLE_ID) REFERENCES EMPLOYEE_ROLE_MASTER (ID)
  );
CREATE SEQUENCE EMPLOYEE_MASTER_SEQ INCREMENT BY 1 START WITH 1;